// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdqbyrijeyymxgvejwsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kcWJ5cmlqZXl5bXhndmVqd3NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjQ2NTYsImV4cCI6MjA2NjAwMDY1Nn0.MHdtVhorBtG9aQ366o7__Hk1SBSaO9aPZ8PUoEmquAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);